### ISSUE TITLE
[suggestion] need explanation about the pattern.

### ISSUE THREAD

**Issue by kraiztmatte** [gothinkster/laravel-realworld-example-app#7]
Hello,
i saw this repo and seems great, but i feel a bit confusing about the design pattern itself inside the code. it looks like repository pattern but some logic are coupled in controller.

i wanted learn from this repo maybe the author would explain the pattern used, and why, so i and everyone (maybe) who read this repo could understand and learn from this repo in building api better with laravel.

thank you.

**Comment by SandeeshS** [comment]
@kraiztmatte sorry if it's a big confusing. There's no repository pattern or any particular style used here. The objective was to keep the code as simple and straightforward as possible without too much dependency on third party packages. Though using repositories would've made things a bit easier, i did not want new Laravel users to get overwhelmed with the concept of using repositories over Eloquent models.
