### ISSUE TITLE
Request: Add role based permissions with Zizaco Entrust or similar.

### ISSUE THREAD

**Issue by ToniAlvarez** [gothinkster/laravel-realworld-example-app#8]
In many realworld webapps role based permissions are a requirement. Please, add Zizaco Entrust or similar to the example.

**Comment by SandeeshS** [comment]
@ToniAlvarez I'd love to add those but this project adheres to the main specs set for all the code bases to retain similar functionality. If the main specs get updated with roles and permissions requirement then i will definitely add a custom and easy implementation as i already have experience implementing with such functionality.
