### ISSUE TITLE
SQLSTATE[42000} error

### ISSUE THREAD

**Issue by tofanelli** [gothinkster/laravel-realworld-example-app#9]
Hey guys... how's going? Hope ok...

I'm trying to install and got this error...

> F:\laravel-realworld-example-app>php artisan migrate
> Migration table created successfully.
> 
>   [Illuminate\Database\QueryException]
>   SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
>   oo long; max key length is 1000 bytes (SQL: alter table `users` add unique
>   `users_username_email_unique`(`username`, `email`))
> 
>   [PDOException]
>   SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
>   oo long; max key length is 1000 bytes

But, according this issue [here](https://github.com/laravel/framework/issues/17508#issuecomment-274881144), what it could be done is already implemented by you guys.... 

It creates two tables (migrations and users), and nothing else... 

So, what should I do?

Cheers =)

**Comment by tofanelli** [comment]
Update

I "fixed" using [this solution](https://stackoverflow.com/posts/39750202/revisions) from Stack.. I'm not quite sure if I could do this, but, I think its working.

Now I'm seeing a Laravel homepage... is that right?


Cheers =)

**Comment by SandeeshS** [comment]
@tofanelli It's a documented issue with index length on older versions of MySQL and MaridaDB. You can check the documentation about it. If you got it working with that fix then don't worry about it.

https://laravel.com/docs/5.4/migrations#creating-indexes

**Comment by eissasoubhi** [comment]
From the Laravel doc 
``` If you are running a version of MySQL older than the 5.7.7 release or MariaDB older than the 10.2.2 release, you may need to manually configure the default string length ```

I'm using MySQL 5.7.19 and with your fix with ``Schema::defaultStringLength``, **I'm still having that error.**

Any ideas?
